version: "3"

services:
  db:
    image: postgres:12
    environment:
      POSTGRES_USER: clown_user
      POSTGRES_PASSWORD: clown_password
      POSTGRES_DB: clown_db
    ports:
      - "5432:5432"

  authentication_service:
    build: ./authentication_service
    ports:
      - "5001:5000"
    links:
      - db
    environment:
      FLASK_APP: views.py
      FLASK_ENV: development
      DATABASE_URL: postgresql://clown_user:clown_password@db:5432/clown_db
    depends_on:
      - db

  client_service:
    build: ./client_service
    ports:
      - "5002:5000"
    links:
      - db
    environment:
      FLASK_APP: views.py
      FLASK_ENV: development
      DATABASE_URL: postgresql://clown_user:clown_password@db:5432/clown_db
    depends_on:
      - db
      - authentication_service

  troupe_leader_service:
    build: ./troupe_leader_service
    ports:
      - "5003:5000"
    environment:
      FLASK_APP: views.py
      FLASK_ENV: development
      DATABASE_URL: postgresql://clown_user:clown_password@db:5432/clown_db
    depends_on:
      - db

  clown_service:
    build: ./clown_service
    ports:
      - "5004:5000"
    environment:
      FLASK_APP: views.py
      FLASK_ENV: development
      DATABASE_URL: postgresql://clown_user:clown_password@db:5432/clown_db
    depends_on:
      - db
